### ISSUE TITLE
[US 6.1] DB Management Task

### ISSUE THREAD

**Issue by Dragris** [UB-ES-2021-A4/Booksy#5]
The data base that is going to be used for the project is PostgreSQL 14.

This data base will ensure that the application can run with top speed while giving us more query support than SQLite3.
A wiki post will be written with the steps that we have to follow to add or edit tables to the database.

**Comment by Dragris** [comment]
I've written a small article in the project's wiki to show how to add and modify tables to the database. If there's additional information that needs to be added, please contact me or refer to the official Django documentation to find more information.

**Comment by saguillo2000** [comment]
Tomorrow we need to talk if during the development use sqlite3 or Posgre. I found a lot of issues in the Posgre14
